### ISSUE TITLE
Kubernetes dashboard chart fails to install

### ISSUE THREAD

**Issue by maratoid** [samsung-cnct/k2#81] opened 2016-11-06 04:17 UTC
dashboard chart (https://github.com/samsung-cnct/k2-charts/tree/master/kubernetes-dashboard)

fails to install with helm beta2 with error:

"Error: release dashboard failed: unable to decode \"\"

**Comment by coffeepac** [comment] 2017-01-25 21:40
this may be working already.  verify.

**Comment by leahnp** [comment] 2017-02-18 21:09
I have not been able to reproduce this error. I did get the error: 

`Error: release snug-guppy failed: error validating "": error validating data: expected type int, for field spec.replicas, got string`

Which I fixed with the following PR - dashboard installs and works fine for me at this time.

**Comment by davidewatson** [comment] 2017-02-21 17:58
Works for me.

```
rodin:k2cli dwat$ ./k2cli tool helm --config /Users/dwat/.kraken/dewVanilia.yaml install atlas/kubernetes-dashboard
Using k2 config file: /Users/dwat/.kraken/dewVanilia.yaml
NAME:   billowing-chicken
LAST DEPLOYED: Tue Feb 21 17:57:58 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                   CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
kubernetes-dashboard   10.43.27.227   <pending>     80:32299/TCP   1s

==> extensions/Deployment
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kubernetes-dashboard   1         1         1            0           1s


rodin:k2cli dwat$ 
```

**Closed by davidewatson** 2017-02-21 17:58 UTC
Labels: bug, K2, priority-p1

**Comment by coffeepac** [comment] 2017-02-21 18:02
late to the party, but wfm as well as part of the k2cli configuration file.
