### ISSUE TITLE
rationalize username/hostpath for multiple OS support

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#727] opened 2017-08-09 17:17 UTC
as part of the bastion node project we are dropping an ssh config file onto the bastion nodes for ease-of-ssh access.  this means kraken needs to have some knowledge of the remote OS's user name and home directory.  

we should either:
a. set the username as part of the node boot process
b. set the username as part of the OSConfig stanza and template out the scp commands

**Comment by alejandroEsc** [comment] 2017-08-09 17:36
The problem with having to put (username/path) as part of the OS config is that, and maybe im wrong here, but the user would assume that they can put any value there, including path and it would mean that coreos will have their new username and path there when brought up. Not sure if that is what we would mean by adding it to the schema. Do we have a concept of internal schema vs inflight user schema definitions?

**Comment by joejulian** [comment] 2017-08-09 17:59
Duplicate of #405

**Closed** 2017-08-09 20:32 UTC
Labels: K2, multi-OS Support
