### ISSUE TITLE
K2 Up Ending Usage Could Be Clearer

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#98] opened 2016-11-17 19:39 UTC
K2 should be able to customize this output with the values for the system that just started:

```
LAY RECAP *********************************************************************
localhost                  : ok=123  changed=86   unreachable=0    failed=0

To use kubectl:
kubectl --kubeconfig=~/.kraken/<cluster name>/admin.kubeconfig <kubctl command>

For example:
kubectl --kubeconfig=~/.kraken/krakenCluster/admin.kubeconfig get services --all-namespaces
To use helm:
KUBECONFIG=~/.kraken/<cluster name>/admin.kubeconfig; helm <helm command> --home ~/.kraken/<cluster name>/.helm
For example:
KUBECONFIG=~/.kraken/krakenCluster/admin.kubeconfig; helm list --home ~/.kraken/krakenCluster/.helm

To ssh:
ssh <node pool name>-<number> -F ~/.kraken/<cluster name>/ssh_config
For example:
ssh masterNodes-3 -F ~/.kraken/krakenCluster/ssh_config
```

e.g. < cluster name >  and ~/ 

 `~/`  in --kubeconfig does not work (on some systems).  It needs to be the full pathname.

**Comment by coffeepac** [comment] 2016-12-01 19:11
yeah, that's always bothered me.  <cluster name> should be available.  and in fact the entire path should be there if --output is used.

**Comment by coffeepac** [comment] 2017-04-05 21:35
this is a dupe of something that just compeled.

**Closed by coffeepac** 2017-04-05 21:35 UTC
Labels: feature request, K2, priority-p2
