### ISSUE TITLE
Unable to ./bin/update.sh --addnodepools

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2#793] opened 2017-09-01 05:41 UTC
Running in cluster, the following `./bin/update.sh --addnodepools` fails during the terraform dryrun:

```
TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Run terraform dryrun update] ***
FAILED - RETRYING: Run terraform dryrun update (10 retries left).
FAILED - RETRYING: Run terraform dryrun update (9 retries left).
FAILED - RETRYING: Run terraform dryrun update (8 retries left).
FAILED - RETRYING: Run terraform dryrun update (7 retries left).
FAILED - RETRYING: Run terraform dryrun update (6 retries left).
FAILED - RETRYING: Run terraform dryrun update (5 retries left).
FAILED - RETRYING: Run terraform dryrun update (4 retries left).
FAILED - RETRYING: Run terraform dryrun update (3 retries left).
FAILED - RETRYING: Run terraform dryrun update (2 retries left).
FAILED - RETRYING: Run terraform dryrun update (1 retries left).
```

All of the system artifacts are in place on the running Pod:
```
$ kubectl exec -c krak8s krak8s-krak8s-3933751286-x33nr -n krak8s -i -t -- ash
```
I'll link the log file here as soon as I'm able to redact it for sensitive information.

The persistent `config.yaml` and `.kraken/cluster` data is also persisted in the colonybead-state private repository.

**Comment by sostheim** [comment] 2017-09-01 05:44
Uploaded kraken update.sh log output: [newjersey_nodepool_updated_addnodepools_failed.txt](https://github.com/samsung-cnct/k2/files/1269244/newjersey_nodepool_updated_addnodepools_failed.txt)

**Comment by davidewatson** [comment] 2017-09-01 15:59
This is occurring because the `prevent_destroy` flag is set to true except when `kraken_action == 'down'`:

> * aws_instance.etcdEvents_5: the plan would destroy this resource, but it currently has lifecycle.prevent_destroy set to true. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or adjust the scope of the plan using the -target flag.

I suspect `userdata` is changing which causes terraform to attempt to recreate the etcd nodes (maybe related to #792).

**Comment by davidewatson** [comment] 2017-09-01 16:06
The problem is we are not passing `-target` to the `terraform apply` task in `ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action-dryrun.yaml`.

**Comment by davidewatson** [comment] 2017-09-01 17:49
#795 should fix this. Please retest. Note that in `kraken.provider.aws.tf.jinja2` we still have a forced dependency which should no longer be necessary. I don't _think_ it hurts anything though, so I am leaving it until after the ticket is resolved.

**Comment by davidewatson** [comment] 2017-09-06 17:26
Closing this due to the fix above. Please reopen if it reoccurs.

**Closed by davidewatson** 2017-09-06 17:26 UTC
